[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
warn_unreachable = True
implicit_reexport = False
no_implicit_optional = True
strict_equality = True
strict_optional = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
explicit_package_bases = True
namespace_packages = True
exclude = (?x)(
    ^data/
    | ^docs/
    | ^infra/
    | ^automation/playwright/node_modules/
    | __pypackages__
    | \.venv
    )

[mypy-tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False
